- name: Configure basic settings on the router
  hosts: all
  connection: local
  vars:
    - username: "ansible"
    - password: "ansible"
  tasks:
    - name: Configure hostname
      ios_config:
        host: "{{ ansible_ssh_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        lines:
          - hostname {{ inventory_hostname }}

    - name: Remove ACL from vty
      ios_config:
        host: "{{ ansible_ssh_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        lines:
          - no access-class VTY_ACL in
        parents: ['line vty 0 4']

    - name: Configure ACL
      ios_config:
        host: "{{ ansible_ssh_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        lines:
           - deny   ip host 192.168.35.111 any
           - permit ip 192.168.35.0 0.0.0.255 any
        parents: ['ip access-list extended VTY_ACL']
        before: ['no ip access-list extended VTY_ACL']
        match: exact

    - name: Apply ACL
      ios_config:
        host: "{{ ansible_ssh_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        lines:
          - access-class VTY_ACL in
        parents: ['line vty 0 4']

    - name: Add SNMP community
      ios_config:
        host: "{{ ansible_ssh_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        lines:
          - snmp-server community {{ snmp.community }} RO

    - name: Configure banner
      ios_template:
        host: "{{ ansible_ssh_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        src: ./templates/banner.j2
   
