- name: Get the list of interfaces from the routers and store the list to the file
  hosts: all
  connection: local
  vars:
    - username: "cisco"
    - password: "cisco"
  tasks:
    - name: Execute show ip interface brief command
      ios_command:
        host: "{{ ansible_ssh_host }}"
        username: "{{ username }}"
        password: "{{ password }}" 
        commands:
          - show ip interface brief
      register: router_output

    - name: Print the lines with the GigabitEthernet interface
      debug: var=item
      with_items: "{{ router_output.stdout_lines }}"
      when: item | search("^Gigabit.*") | regex_replace('\s+', ' ') 

    - name: Create file if the file does not exists
      file: path=./output_{{ inventory_hostname }}.txt state=touch

    - name: Copy output lines to the file
      lineinfile:
        line={{ item }} 
        dest=./output_{{ inventory_hostname }}.txt
        regexp="{{ item | regex_replace('(?P<int>GigabitEthernet[0-9]).*', '\\g<int>') }}"
      with_items: "{{ router_output.stdout_lines }}"
      when: item | search("^Gigabit.*")
