- name: Get interfaces from the routers
  hosts: all
  connection: local
  vars:
    - username: "cisco"
    - password: "cisco"
  tasks:
    - name: test show command
      ios_command:
        host: "{{ ansible_ssh_host }}"
        username: "{{ username }}"
        password: "{{ password }}" 
        commands:
          - show ip interface brief
      register: router_output

    - name: print output
      debug: var=item
      with_items: "{{ router_output.stdout_lines }}"
      when: item | search("^Gigabit.*") | regex_replace('\s+', ' ') 

    - name: Create file if file does not exists
      file: path=/home/ubajzelj/SINOG/output_{{ inventory_hostname }}.txt state=touch

    - name: copy to file
      lineinfile:
        line={{ item }} 
        dest=/home/ubajzelj/SINOG/output_{{ inventory_hostname }}.txt
        regexp="{{ item | regex_replace('(?P<int>GigabitEthernet[0-9]).*', '\\g<int>') }}"
      with_items: "{{ router_output.stdout_lines }}"
      when: item | search("^Gigabit.*")
