- name: Get softwere version from routers
  hosts: all
  connection: local
  vars:
    - username: "cisco"
    - password: "cisco"
  tasks:
    - name: Execute show version command on all routers
      ios_command:
        host: "{{ ansible_ssh_host }}"
        username: "{{ username }}"
        password: "{{ password }}" 
        commands:
          - show version
      register: router_output

# Use named regex to get <ver> variable, which can be used later...
    - name: Print software version to the screen
      debug: msg="{{ router_output.stdout | regex_replace('.* (?P<ver>Version [0-9]{2}\.[0-9]{2}\.[0-9]{2}\.. ).*', '\\g<ver>') }}"

